name: Python CI

on:
  push:
    branches:
      - master  # Quando um push for feito para a branch 'master'
  pull_request:
    branches:
      - master  # Quando um pull request for feito para a branch 'master'
  workflow_dispatch:  # Gatilho manual para execução direta

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente de execução (Ubuntu)

    steps:
      # Faz o checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Instala as dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt  # Instala as dependências do seu projeto

      # Instala o pytest (caso não esteja em requirements.txt)
      - name: Install pytest
        run: |
          python -m pip install pytest  # Garante que pytest seja instalado

      # Verifica se o pytest foi instalado corretamente
      - name: Verify pytest installation
        run: |
          pip show pytest  # Verifica se o pytest está instalado corretamente

      # Executa os testes automatizados com pytest
      - name: Run tests
        run: |
          pytest  # Executa os testes
